/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useEffect } from 'react'
import { useGLTF } from '@react-three/drei'

import { useBox, useContactMaterial } from '@react-three/cannon'


const groundMaterial = 'ground'
const popcornMaterial = 'popcorn'

export function PopcornModel(props) {
  const { nodes, materials } = useGLTF('/popcorn-draco.glb')

  const xPos = (Math.random() - 0.5) * 3
  const yPos = 5
  const zPos = (Math.random() - 0.5) * 3

  const [ref, api] = useBox(() => ({
    args: [2*props.scale, 2.5*props.scale, 2*props.scale],
    position: [xPos, yPos, zPos],
    material: popcornMaterial,
    mass: 1,
    ...props
  }))

  useContactMaterial(popcornMaterial, groundMaterial, {
    friction: 0.9,
    restitution: 0.3,
  })

  useEffect(() => {
    const randX = (Math.random() - 0.5) * 4
    const randY = Math.random() * 5 + 8
    const randZ = (Math.random() - 0.5) * 4
    api.applyImpulse([randX, randY, randZ], [0.05,0.1,0])
  }, [])

  return (
    <group ref={ref} {...props} dispose={null}>
      <group position={[0.01, -1, 0.01]}>
        
        <mesh geometry={nodes.Icosphere001_1.geometry} material={materials.Butter} />
        <mesh geometry={nodes.Icosphere001_2.geometry} material={materials.ButterLess} />
        <mesh geometry={nodes.Icosphere001_3.geometry} material={materials.Seed} />
      </group>
      <group position={[2.8, -1, 0.01]}>
        <mesh geometry={nodes.Icosphere002_1.geometry} material={materials.Butter} />
        <mesh geometry={nodes.Icosphere002_2.geometry} material={materials.ButterLess} />
        <mesh geometry={nodes.Icosphere002_3.geometry} material={materials.Seed} />
      </group>
      <group position={[2.8, -0.75, 0.01]}>
        <mesh geometry={nodes.Icosphere003_1.geometry} material={materials.Butter} />
        <mesh geometry={nodes.Icosphere003_2.geometry} material={materials.ButterLess} />
        <mesh geometry={nodes.Icosphere003_3.geometry} material={materials.Seed} />
      </group>
      <group position={[2.16, -1.34, 1.77]}>
        <mesh geometry={nodes.Icosphere004.geometry} material={materials.Butter} />
        <mesh geometry={nodes.Icosphere004_1.geometry} material={materials.ButterLess} />
        <mesh geometry={nodes.Icosphere004_2.geometry} material={materials.Seed} />
      </group>
    </group>
  )
}

useGLTF.preload('/popcorn-draco.glb')
