/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useTexture, MeshPortalMaterial, Plane, Box, Sphere } from '@react-three/drei'
import { extend, useFrame } from '@react-three/fiber'
import * as THREE from 'three'

import { PortalMaterial } from './shaders/portal'
extend({ PortalMaterial })

export default function Portal(props) {
  const { nodes, materials } = useGLTF('/portal-transformed.glb')
  const portalMaterialRef = useRef()
  const bakedTexture = useTexture('/bakedFinal.jpg')

  useFrame((state, delta) => (portalMaterialRef.current.uTime += delta))

  return (
    <group {...props} dispose={null} rotation={[0, Math.PI, 0]}>
      <mesh geometry={nodes.poleLightB.geometry} material-color="#f77e60" position={[-0.68, 0.76, -0.24]} rotation={[0, -1.54, 0]} />
      <mesh geometry={nodes.poleLightA.geometry} material-color="#f77e60" position={[0.72, 0.76, -0.77]} rotation={[-Math.PI, 1.56, -Math.PI]} />
      <mesh geometry={nodes.portalLight.geometry} position={[0, 0.95, 1.78]} rotation={[-Math.PI / 2, 0, 0]}>
        <MeshPortalMaterial transparent blend={0.0}>
          <ambientLight intensity={0.5} />
          <spotLight castShadow color={'orange'} intensity={2} position={[10, 10, 10]} angle={0.15} penumbra={1} shadow-normalBias={0.05} shadow-bias={0.0001} />
          <Sphere rotation={[-Math.PI/2, 0, 0]} position={[0,0,0]} scale={0.7}>
            <portalMaterial ref={portalMaterialRef} side={THREE.BackSide}/>
          </Sphere>
          <mesh scale={[0.2,0.2,0.2]} rotation={[Math.PI/2, 0, 0]} position={[0,-0.7,0]}>
            <torusGeometry args={[0.40, 0.09, 7, 6]}/>
            <meshToonMaterial color={'orange'} />
          </mesh>
          <mesh scale={[0.5,0.5,0.5]} rotation={[Math.PI/2, 0, 0]} position={[0,-0.5,0]}>
            <torusGeometry args={[0.40, 0.05, 7, 6]}/>
            <meshToonMaterial color={'orange'} />
          </mesh>
          <mesh scale={[1,1,1]} rotation={[Math.PI/2, 0, 1.7]} position={[0,-0.2,0]}>
            <torusGeometry args={[0.40, 0.04, 7, 6]}/>
            <meshToonMaterial color={'orange'} />
          </mesh>
          <mesh scale={[1.5,1.5,1.5]} rotation={[Math.PI/2, 0, 2.4]}>
            <torusGeometry args={[0.40, 0.04, 7, 6]}/>
            <meshToonMaterial color={'orange'} />
          </mesh>
        </MeshPortalMaterial>
      </mesh>
      <mesh geometry={nodes.baked.geometry}>
        <meshBasicMaterial map={bakedTexture} map-flipY={false} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/portal-transformed.glb')
