/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Burger(props) {
  const { nodes, materials } = useGLTF('/burger-draco.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow  geometry={nodes.bunBottom.geometry} material={materials.bunMaterial} />
      <mesh castShadow geometry={nodes.meatOne.geometry} material={materials.meatMaterial} position={[0, 1.58, 0]} />
      <mesh castShadow geometry={nodes.CheeseOne.geometry} material={materials.cheeseMaterial} position={[0, -0.39, 0]} />
      <mesh castShadow geometry={nodes.bunTop.geometry} material={materials.bunMaterial} position={[0, 4.03, 0]} rotation={[0, 0, Math.PI]} />
      <mesh castShadow geometry={nodes.meatTwo.geometry} material={materials.meatMaterial} position={[0, 3.11, 0]} />
      <mesh castShadow geometry={nodes.CheeseTwo.geometry} material={materials.cheeseMaterial} position={[0, 0.5, 0]} rotation={[0, 0.78, 0]} />
    </group>
  )
}

useGLTF.preload('/burger-draco.glb')
